config/routes.rb
ShutaidongBe::Application.routes.draw do
  resources :taidongs

  resources :accounts

  root 'welcome#index'

  namespace :admin do
    resources :accounts do
      resources :taidons
    end
  end
end

app/models/account.rb
require 'digest/sha1'

class Account < ActiveRecord::Base
  has_many :taidongs, :dependent => :destroy
  validates :email, :presence => true
  validate :password_is_valid, :on => :create

  attr_accessor :password

  def password=(new_password)
    self.salt = SecureRandom.hex(10)
    self.encrypted_password = encrypt_password(new_password)
  end

  def password_valid?(possible_password)
    self.encrypted_password == encrypt_password(possible_password)
  end

  def password_is_valid
    self.password.present?
  end

  def encrypt_password(new_pass)
    Digest::SHA1.hexdigest(self.salt + "shutaidong" + new_pass)
  end
end

app/models/taidong.rb
class Taidong < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def create
    @account = Account.new params[:account]
    if @account.save
      head :success
    else
      head :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:email, :encrypted_password, :salt, :last_sync_at)
    end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/taidongs_controller.rb
class Admin::TaidongsController < Admin::BaseController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/taidongs_controller.rb
class TaidongsController < ApplicationController
  before_action :set_taidong, only: [:show, :edit, :update, :destroy]
  before_filter :authentication

  def index
    render :json => @account.taidongs
  end

  def create
    @account.taidongs << params[:taidongs]
    @account.last_sync_at = Time.no
    if @account.save
      head :success
    else
      head :unprocessable_entity
    end
  end



  private

  def set_taidong
    @taidong = Taidong.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def taidong_params
    params.require(:taidong).permit(:happened_at, :account_id, :batch_id)
  end

  def authentication
    authenticate_or_request_with_http_basic do |email, password|
      @account = Account.find_by_email email
      @account.password_valid? password
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taidongs_helper.rb
module TaidongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :encrypted_password %><br>
    <%= f.text_field :encrypted_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="field">
    <%= f.label :last_sync_at %><br>
    <%= f.datetime_select :last_sync_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Salt</th>
      <th>Last sync at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.email %></td>
        <td><%= account.encrypted_password %></td>
        <td><%= account.salt %></td>
        <td><%= account.last_sync_at %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @account.encrypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @account.salt %>
</p>

<p>
  <strong>Last sync at:</strong>
  <%= @account.last_sync_at %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShutaidongBe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/taidongs/_form.html.erb
<%= form_for(@taidong) do |f| %>
  <% if @taidong.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taidong.errors.count, "error") %> prohibited this taidong from being saved:</h2>

      <ul>
      <% @taidong.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :happened_at %><br>
    <%= f.datetime_select :happened_at %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :batch_id %><br>
    <%= f.text_field :batch_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taidongs/edit.html.erb
<h1>Editing taidong</h1>

<%= render 'form' %>

<%= link_to 'Show', @taidong %> |
<%= link_to 'Back', taidongs_path %>

app/views/taidongs/index.html.erb
<h1>Listing taidongs</h1>

<table>
  <thead>
    <tr>
      <th>Happened at</th>
      <th>Account</th>
      <th>Batch</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @taidongs.each do |taidong| %>
      <tr>
        <td><%= taidong.happened_at %></td>
        <td><%= taidong.account_id %></td>
        <td><%= taidong.batch_id %></td>
        <td><%= link_to 'Show', taidong %></td>
        <td><%= link_to 'Edit', edit_taidong_path(taidong) %></td>
        <td><%= link_to 'Destroy', taidong, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taidong', new_taidong_path %>

app/views/taidongs/new.html.erb
<h1>New taidong</h1>

<%= render 'form' %>

<%= link_to 'Back', taidongs_path %>

app/views/taidongs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Happened at:</strong>
  <%= @taidong.happened_at %>
</p>

<p>
  <strong>Account:</strong>
  <%= @taidong.account_id %>
</p>

<p>
  <strong>Batch:</strong>
  <%= @taidong.batch_id %>
</p>

<%= link_to 'Edit', edit_taidong_path(@taidong) %> |
<%= link_to 'Back', taidongs_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>